<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>

    <#if Error??>
        <#list Error as e>
            ${e.field} error
        </#list>
    </#if>
    <form method="post" action="/templates/user/create">
        <div class="input-field">
            <label for="username">Username</label>
            <input name="username" id="username">
        </div>
        <div class="input-field">
            <label for="password">Password</label>
            <input name="password" id="password" type="password">
        </div>
        <button type="submit">Add</button>
    </form>
</body>
</html>